# Generated by Django 4.2.13 on 2025-01-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starplanner', '0005_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appuser',
        ),
    ]
