# Generated by Django 4.2.17 on 2025-01-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starplanner', '0006_delete_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=100),
        ),
    ]
